"""updated Instructor

Revision ID: b14efd65bcf9
Revises: c3d5336d6d9c
Create Date: 2025-04-10 09:29:10.221066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b14efd65bcf9'
down_revision = 'c3d5336d6d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
