"""added test users and updated instrutor table

Revision ID: c3d5336d6d9c
Revises: a7daaf1939b4
Create Date: 2025-04-10 09:01:21.886368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3d5336d6d9c'
down_revision = 'a7daaf1939b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
