"""created invoice model

Revision ID: f3751ad56b2c
Revises: b14efd65bcf9
Create Date: 2025-04-15 07:46:09.956582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3751ad56b2c'
down_revision = 'b14efd65bcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_template_settings', schema=None) as batch_op:
        batch_op.drop_constraint('invoice_template_settings_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_template_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoice_template_settings_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
